#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d 1 2
bspc monitor HDMI-0 -d 3 4 5 6 7 8 9
bspc wm -0 HDMI-1 HDMI-0

# Truncate a couple of common commands that are used herein.
_bc() {
	bspc config "$@"
}

#### BSPWM configuration ####
_bc window_gap			8
_bc top_padding			26
_bc -m HDMI-1 top_padding	1
_bc top_monocle_padding		0
_bc border_width		2
_bc bottom_padding		0
_bc left_padding		0
_bc right_padding		0
_bc single_monocle		false
_bc click_to_focus		true
_bc split_ratio			0.50
_bc borderless_monocle		true
_bc gapless_monocle		true
_bc focus_by_distance		true
_bc paddingless_monocle		true
# _bc focus_follows_pointer	true
# _bc ignore_ewmh_focus		true
_bc history_aware_focus		true
_bc remove_disabled_monitors	true
_bc merge_overlapping_monitors	true
# _bc pointer_follows_monitor	true
# _bc pointer_modifier		mod1
# _bc pointer_action1		move
# _bc pointer_action2		resize_side
# _bc pointer_action3		resize_corner

# Colors
bspc config active_border_color "#474f54"
bspc config focused_border_color "#5e8dab" # "#57aade" # "#474f54"
bspc config normal_border_color "#373d41"
bspc config presel_feedback_color "#373d41"


# Rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Blueman-manager -o desktop="^8" follow=off focus=off hidden=on
# bspc rule -a zoom state=floating center=on follow=on border=off sticky=on rectangle=1200x800

feh --bg-scale ~/.config/wallpapers/astronaut.jpg

# set screen timeout to 1 hour
# xset s 3600 3600
~/.config/polybar/launch.sh &
/usr/bin/dunst &
# /usr/bin/blueman-manager &
/usr/bin/picom &


# auto launch applications
# sleep 2
# ~/.config/bspwm/autostart.sh &
